{{- if $.Values.externalSecretStore.create }}

{{ $projects := list }}
{{ range $v := $.Values.iamPolicy.secretRoles }}
{{ $projects = append $projects $v.project }}
{{ end }}

{{ range $p := uniq $projects }}
### {{$p}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ printf "secstore-%s" $p | trunc 63 | trimSuffix "-" }}
spec:
  provider:
    gcpsm:
      projectID: {{ $p }}
      auth:
        workloadIdentity:
          clusterLocation: {{ $.Values.iamPolicy.gke.clusterLocation }}
          clusterName: {{ $.Values.iamPolicy.gke.clusterName }}
          clusterProjectID: {{ $.Values.iamPolicy.gke.clusterProjectID }}
          serviceAccountRef:
            name: {{ $.Values.iamPolicy.gke.serviceAccount }}
{{- end }}

{{- end }}
