global:
  imagePullPolicy: Always
  serviceAccount:
    create: true
    name: change-me
    # annotations: []
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
deployments: {}

additionalManifests: []
additionalYamlManifests: ""
